import {formatBytes,inferMime,cleanFilename} from './ic2-util.js';
import {getKnowledgeSnapshot,learnSamples,knowledgeSummary,clearKnowledge,trainFromArchiveOrg} from './ic2-knowledge.js';
const $=s=>document.querySelector(s),els={input:$('#file-input'),drop:$('#drop-zone'),add:$('#add-more'),clear:$('#clear-queue'),shell:$('#batch-shell'),queue:$('#file-queue'),count:$('#batch-count'),run:$('#create-links'),cancel:$('#cancel-batch'),ow:$('#overall-progress-wrap'),op:$('#overall-progress'),os:$('#overall-status'),pct:$('#overall-percent'),out:$('#outputs-panel'),outList:$('#outputs-list'),copyAll:$('#copy-all'),qt:$('#queue-row-template'),ot:$('#output-row-template'),ks:$('#knowledge-status'),archive:$('#train-archive'),clearK:$('#clear-knowledge')};
let q=[],id=1,worker=null,current=null,running=false,cancelled=false;
const ext=n=>{const p=String(n).split('.');return p.length>1?(p.pop().replace(/[^a-z0-9]/gi,'').slice(0,5).toUpperCase()||'FILE'):'FILE'};
const shareUrl=(token,name)=>{const u=new URL('./s/',location.href);u.hash=`${token}/${encodeURIComponent(cleanFilename(name))}`;return u.toString()};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function memory(extra=''){try{const s=await knowledgeSummary();els.ks.textContent=`PRIVATE MEMORY ${s.samples.toLocaleString()} samples · ${s.profiles.toLocaleString()} profiles · ${s.files.toLocaleString()} files · ${formatBytes(s.bytes)} observed.${s.publicProfiles?` PUBLIC BASELINE ${s.publicProfiles.toLocaleString()} profiles · ${s.publicFiles.toLocaleString()} files · ${formatBytes(s.publicBytes)} observed.`:''}${extra?` ${extra}`:''}`}catch{els.ks.textContent='CORRIDOR MEMORY UNAVAILABLE IN THIS BROWSER.'}}
function detail(stats){const rows=Object.entries(stats?.byKind||{}).sort((a,b)=>b[1]-a[1]).map(([n,b])=>`<div class="rep-row"><span>${esc(n)}</span><strong>${formatBytes(b)}</strong></div>`).join('');if(!rows)return'';const k=stats?.knowledge||{},c=stats?.corpus||{};return `<div class="rep-grid">${rows}</div>${c.matchedChunks?`<div class="knowledge-gain">CORPUS MATCH · ${Number(c.matchedChunks).toLocaleString()} CHUNKS · ${formatBytes(c.matchedBytes||0)} REFERENCED · ${Number(c.distinctSources||0).toLocaleString()} SOURCES</div>`:''}${k.dictionaryUsed?`<div class="knowledge-gain">ADAPTIVE MEMORY USED · ${Number(k.dictionaryUses||0).toLocaleString()} CHUNKS · NET ${formatBytes(k.dictionarySavings||0)} SAVED</div>`:k.availableDictionaryBytes?'<div class="knowledge-gain muted">ADAPTIVE MEMORY TESTED · ORDINARY REPRESENTATION REMAINED SMALLER.</div>':''}<div class="rep-foot">${Number(stats.chunks||0).toLocaleString()} CHUNKS → ${Number(stats.segments||0).toLocaleString()} SEGMENTS · ${formatBytes(stats.embeddedBytes||0)} EMBEDDED</div>`}
function state(x){return x.status==='running'?['ENCODING','state-running']:x.status==='success'?['RECOVERED','state-success']:x.status==='error'?['FAILED','state-error']:['WAITING','state-waiting']}
function render(){els.queue.textContent='';for(const x of q){const f=els.qt.content.cloneNode(true),r=f.querySelector('.queue-row');r.classList.toggle('is-running',x.status==='running');r.classList.toggle('is-success',x.status==='success');r.classList.toggle('is-error',x.status==='error');r.querySelector('.queue-icon').textContent=ext(x.file.name);r.querySelector('.queue-name').textContent=x.file.name;r.querySelector('.queue-meta').textContent=`${formatBytes(x.file.size)} · ${x.file.type||inferMime(x.file.name)}`;const [lab,cl]=state(x),st=r.querySelector('.queue-state');st.textContent=lab;st.className=`queue-state ${cl}`;r.querySelector('.queue-message').textContent=x.msg||'Awaiting initiation.';const pw=r.querySelector('.queue-progress-wrap');if(x.status==='running'||x.progress){pw.hidden=false;pw.querySelector('progress').value=x.progress||0;pw.querySelector('span').textContent=`${Math.round((x.progress||0)*100)}%`}const d=r.querySelector('.queue-details');if(x.details){d.innerHTML=x.details;d.hidden=false}const retry=r.querySelector('.retry-file');retry.hidden=x.status!=='error'||running;retry.onclick=()=>retryOne(x.id);const rm=r.querySelector('.remove-file');rm.disabled=running&&current===x;rm.onclick=()=>remove(x.id);els.queue.appendChild(f)}els.shell.hidden=!q.length;els.drop.hidden=!!q.length;els.count.textContent=`${q.length} object${q.length===1?'':'s'}`;els.clear.disabled=running||!q.length;els.run.disabled=running||!q.some(x=>x.status!=='success');outputs();overall()}
function outputs(){const good=q.filter(x=>x.status==='success'&&x.url);els.out.hidden=!good.length;els.copyAll.disabled=!good.length;els.outList.textContent='';for(const x of good){const f=els.ot.content.cloneNode(true);f.querySelector('.output-name').textContent=x.file.name;f.querySelector('.output-summary').textContent=x.summary;f.querySelector('.output-link').value=x.url;const c=f.querySelector('.copy-one');c.onclick=()=>copy(x.url,c);f.querySelector('.open-one').onclick=()=>window.open(x.url,'_blank','noopener,noreferrer');els.outList.appendChild(f)}}
function overall(){if(!q.length){els.ow.hidden=true;return}const done=q.filter(x=>['success','error'].includes(x.status)).length,active=q.find(x=>x.status==='running');let v=done/q.length;if(active)v=(done+(active.progress||0))/q.length;els.op.value=Math.min(1,v);els.pct.textContent=`${Math.round(v*100)}%`;if(running)els.os.textContent=active?`Traversing ${active.file.name}`:'Preparing next object…';else{const ok=q.filter(x=>x.status==='success').length,fail=q.filter(x=>x.status==='error').length;els.os.textContent=ok||fail?`${ok} recovered · ${fail} failed · ${q.length-ok-fail} waiting`:'Awaiting initiation.'}els.ow.hidden=!(running||done)}
function add(files){for(const file of Array.from(files||[]))if(file instanceof File)q.push({id:id++,file,status:'waiting',progress:0,msg:'Awaiting initiation.',url:'',summary:'',details:'',knowledge:null});render()}
function remove(n){if(running&&current?.id===n)return;q=q.filter(x=>x.id!==n);render()}
function reset(x,msg='Retry queued.'){Object.assign(x,{status:'waiting',progress:0,msg,url:'',summary:'',details:''})}
function retryOne(n){const x=q.find(v=>v.id===n);if(!x||running)return;reset(x);render();runBatch([x])}
async function knowledge(x){if(x.knowledge)return x.knowledge;try{return x.knowledge=await getKnowledgeSnapshot(x.file)}catch{return null}}
function encode(x){return new Promise(async(resolve,reject)=>{current=x;x.status='running';x.progress=0;x.msg='Opening exact-match corridor…';render();const k=await knowledge(x);if(cancelled)return reject(Object.assign(new Error('Cancelled'),{cancelled:true}));const w=new Worker('./ic2-worker.js?v=20260812corridor2',{type:'module'});worker=w;w.onmessage=async e=>{const m=e.data||{};if(m.type==='progress'){if(m.total&&m.done>=0)x.progress=Math.min(1,m.done/m.total);x.msg=m.phase==='corpus'?`Scanning public corpus · ${Number(m.segments||0).toLocaleString()} segments resolved`:m.phase==='fallback'?'Corpus path insufficient. Entering self-contained IC2 fallback…':m.phase==='pack'?`Sealing ${Number(m.segments||0).toLocaleString()} optimized segments…`:`Analyzing locally · ${Number(m.segments||0).toLocaleString()} segments`;render();return}if(m.type==='error'){w.terminate();if(worker===w)worker=null;reject(Object.assign(new Error(m.message||'Encoder failed.'),{code:m.code}));return}if(m.type==='done'){try{await learnSamples(x.file,m.learningSamples||[],{fileBytes:x.file.size})}catch(err){console.warn('knowledge update failed',err)}const url=shareUrl(m.token,x.file.name),outer=m.outerMode==='Z'?'Zstandard':m.outerMode==='G'?'gzip':'raw',label=m.format==='IC2C'?'IC2C corpus-assisted':'IC2 self-contained';Object.assign(x,{url,summary:`${label} · ${url.length.toLocaleString()} URL chars · ${formatBytes(m.packedBytes)} packed · ${outer}`,details:detail(m.stats),progress:1,status:'success',msg:m.format==='IC2C'?'Recovered through verified public corpus references.':'Recovered as a self-contained exact descriptor.',knowledge:null});w.terminate();if(worker===w)worker=null;resolve(x)}};w.onerror=e=>{w.terminate();if(worker===w)worker=null;reject(new Error(e.message||'The IC2 worker failed.'))};w.postMessage({type:'encode',file:x.file,knowledge:k})})}
async function runBatch(list=null){if(running)return;const targets=list||q.filter(x=>x.status!=='success');if(!targets.length)return;running=true;cancelled=false;els.cancel.hidden=false;els.cancel.disabled=false;els.add.disabled=true;els.ow.hidden=false;render();for(const x of targets){if(cancelled)break;if(x.status==='success')continue;try{await encode(x)}catch(e){if(cancelled||e.cancelled){x.status='waiting';x.progress=0;x.msg='Traversal interrupted.'}else{x.status='error';x.progress=0;x.msg=e.message||String(e)}}current=null;render()}running=false;worker=null;current=null;els.cancel.hidden=true;els.cancel.disabled=false;els.add.disabled=false;cancelled=false;render();await memory();if(q.some(x=>x.status==='success'))els.out.scrollIntoView({behavior:'smooth',block:'nearest'})}
function abort(){if(!running)return;cancelled=true;els.cancel.disabled=true;if(current){current.msg='Abort signal sent. Waiting for encoder to unwind…';render()}try{worker?.postMessage({type:'cancel'})}catch{}}
async function copy(text,b){try{await navigator.clipboard.writeText(text)}catch{const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();document.execCommand('copy');t.remove()}if(b){const old=b.textContent;b.textContent='Copied';setTimeout(()=>b.textContent=old,900)}}
async function feed(){if(running)return;els.archive.disabled=els.clearK.disabled=true;try{els.ks.textContent='CONTACTING ARCHIVE.ORG PUBLIC-DOMAIN CORPUS…';const r=await trainFromArchiveOrg({items:8,onProgress:p=>{els.ks.textContent=p.phase==='download'?`MEMORY FEED ${p.trained+1}/${p.target} · DOWNLOADING ${p.title||'OBJECT'}`:p.phase==='learned'?`MEMORY FEED ${p.trained}/${p.target} · LEARNED ${formatBytes(p.size)}`:`MEMORY FEED · INSPECTING ${p.title||'PUBLIC OBJECT'}`}});q.forEach(x=>x.knowledge=null);await memory(`ARCHIVE FEED ADDED ${r.trained} FILES · ${formatBytes(r.totalBytes)}.`)}catch(e){els.ks.textContent=`ARCHIVE FEED FAILED · ${e.message||e}`}finally{els.archive.disabled=els.clearK.disabled=false}}
els.drop.onclick=()=>els.input.click();els.add.onclick=()=>{if(!running)els.input.click()};els.drop.ondragover=e=>{e.preventDefault();if(!running)els.drop.classList.add('dragging')};els.drop.ondragleave=()=>els.drop.classList.remove('dragging');els.drop.ondrop=e=>{e.preventDefault();els.drop.classList.remove('dragging');if(!running)add(e.dataTransfer?.files)};els.input.onchange=()=>{if(!running)add(els.input.files);els.input.value=''};els.clear.onclick=()=>{if(!running){q=[];render()}};els.run.onclick=()=>runBatch();els.cancel.onclick=abort;els.copyAll.onclick=()=>copy(q.filter(x=>x.status==='success'&&x.url).map(x=>`${x.file.name}\n${x.url}`).join('\n\n'),els.copyAll);els.archive.onclick=feed;els.clearK.onclick=async()=>{if(running)return;els.clearK.disabled=true;try{await clearKnowledge();q.forEach(x=>x.knowledge=null);await memory('PRIVATE MEMORY ERASED. PUBLIC BASELINE UNCHANGED.')}finally{els.clearK.disabled=false}};
render();memory();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=20260812corridor2').catch(()=>{});