import { formatBytes, inferMime, cleanFilename, MAX_TOKEN_CHARS } from './ic2-util.js';

const $=s=>document.querySelector(s);
const fileInput=$('#file-input'),dropZone=$('#drop-zone'),fileCard=$('#file-card'),clearButton=$('#clear-file');
const createButton=$('#create-link'),cancelButton=$('#cancel-encode'),status=$('#status'),resultBox=$('#share-result');
const shareLink=$('#share-link'),copyButton=$('#copy-link'),openButton=$('#open-link'),newLinkButton=$('#new-link');
const progress=$('#encode-progress'),progressText=$('#progress-text'),details=$('#representation-details');
let selectedFile=null,currentUrl='',worker=null,busy=false;
function extension(name){const p=String(name).split('.');return p.length>1?(p.pop().replace(/[^a-z0-9]/gi,'').slice(0,5).toUpperCase()||'FILE'):'FILE';}
function buildShareUrl(token,filename){const u=new URL('./s/',location.href);u.hash=`${token}/${encodeURIComponent(cleanFilename(filename))}`;return u.toString();}
function setBusy(v){busy=v;createButton.disabled=v||!selectedFile;clearButton.disabled=v;dropZone.disabled=v;cancelButton.hidden=!v;progress.hidden=!v;createButton.textContent=v?'Encoding…':'Create share link';}
function resetProgress(){progress.value=0;progressText.textContent='';}
function showFile(file){selectedFile=file;currentUrl='';resultBox.hidden=true;shareLink.value='';document.querySelector('#file-name').textContent=file.name;document.querySelector('#file-size').textContent=formatBytes(file.size);document.querySelector('#file-type').textContent=file.type||inferMime(file.name);document.querySelector('#file-ext').textContent=extension(file.name);dropZone.hidden=true;fileCard.hidden=false;clearButton.hidden=false;createButton.disabled=false;details.hidden=true;status.textContent=`No fixed source-file cap. IC2 streams the source and keeps only the compact representation; the final public token is limited to ${MAX_TOKEN_CHARS.toLocaleString()} characters.`;resetProgress();}
function clearFile(){if(busy)return;selectedFile=null;currentUrl='';fileInput.value='';fileCard.hidden=true;dropZone.hidden=false;clearButton.hidden=true;createButton.disabled=true;resultBox.hidden=true;shareLink.value='';details.hidden=true;status.textContent='Choose a file to begin.';resetProgress();}
function representationHtml(stats){const entries=Object.entries(stats?.byKind||{}).sort((a,b)=>b[1]-a[1]);if(!entries.length)return '';const rows=entries.map(([name,bytes])=>`<div class="rep-row"><span>${name}</span><strong>${formatBytes(bytes)}</strong></div>`).join('');return `<div class="rep-grid">${rows}</div><div class="rep-foot">${stats.chunks.toLocaleString()} CDC chunks → ${stats.segments.toLocaleString()} manifest segments · ${formatBytes(stats.embeddedBytes)} embedded payload</div>`;}
async function createShare(){if(!selectedFile||busy)return;if(worker)worker.terminate();worker=new Worker('./ic2-worker.js?v=20260812ic2',{type:'module'});setBusy(true);resultBox.hidden=true;details.hidden=true;resetProgress();status.textContent='Starting IC2 analysis…';worker.onmessage=async(event)=>{const m=event.data||{};if(m.type==='progress'){if(m.total){progress.value=Math.min(1,m.done/m.total);progressText.textContent=`${Math.round(progress.value*100)}% · ${formatBytes(m.done)} / ${formatBytes(m.total)}`;}status.textContent=m.phase==='pack'?`Packing ${m.segments.toLocaleString()} optimized segments…`:`Analyzing and encoding locally · ${m.segments.toLocaleString()} segments so far`;return;}if(m.type==='error'){currentUrl='';resultBox.hidden=true;status.textContent=m.message;setBusy(false);worker?.terminate();worker=null;return;}if(m.type==='done'){const url=buildShareUrl(m.token,selectedFile.name);currentUrl=url;shareLink.value=url;const mode=m.outerMode==='Z'?'Zstandard':m.outerMode==='G'?'gzip':'raw';document.querySelector('#share-summary').textContent=`IC2 · ${url.length.toLocaleString()} URL characters · ${formatBytes(m.packedBytes)} packed manifest · outer ${mode}`;details.innerHTML=representationHtml(m.stats);details.hidden=false;resultBox.hidden=false;status.textContent='Ready to share. The file never left this browser while the link was being created.';progress.value=1;progressText.textContent='100%';setBusy(false);worker?.terminate();worker=null;resultBox.scrollIntoView({behavior:'smooth',block:'nearest'});return;}};worker.onerror=e=>{status.textContent=e.message||'The IC2 worker failed.';setBusy(false);worker?.terminate();worker=null;};worker.postMessage({type:'encode',file:selectedFile});}
async function copyCurrentLink(){if(!currentUrl)return;try{await navigator.clipboard.writeText(currentUrl);}catch{shareLink.focus();shareLink.select();document.execCommand('copy');}const old=copyButton.textContent;copyButton.textContent='Copied';setTimeout(()=>copyButton.textContent=old,1000);}
dropZone.addEventListener('click',()=>fileInput.click());dropZone.addEventListener('dragover',e=>{e.preventDefault();if(!busy)dropZone.classList.add('dragging');});dropZone.addEventListener('dragleave',()=>dropZone.classList.remove('dragging'));dropZone.addEventListener('drop',e=>{e.preventDefault();dropZone.classList.remove('dragging');if(busy)return;const f=e.dataTransfer?.files?.[0];if(f)showFile(f);});fileInput.addEventListener('change',()=>{const f=fileInput.files?.[0];if(f)showFile(f);});clearButton.addEventListener('click',clearFile);createButton.addEventListener('click',createShare);cancelButton.addEventListener('click',()=>{if(worker){worker.postMessage({type:'cancel'});worker.terminate();worker=null;}setBusy(false);status.textContent='Encoding cancelled.';});copyButton.addEventListener('click',copyCurrentLink);openButton.addEventListener('click',()=>currentUrl&&window.open(currentUrl,'_blank','noopener,noreferrer'));newLinkButton.addEventListener('click',createShare);if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js?v=20260812ic2').catch(()=>{});
